import Head from "next/head";
import { useState } from "react";
import { useGitHub } from "../context/GitHubContext";
import { useRouter } from "next/router";
import axios from "axios";
import LitButton from "@/components/ui/button";
import LitModal from "@/components/ui/modal"; 




export default function Home() {
  const [input, setInput] = useState("");
  const [showModal, setShowModal] = useState(false); 
  const { setUsername, setRepos } = useGitHub();
  const router = useRouter();

  const handleSearch = async () => {
    if (!input) return;
    setUsername(input);

    try {
      const { data } = await axios.get(
        `https://api.github.com/users/${input}/repos`
      );
      
      if (data.length === 0) {
        setShowModal(true); // Jika repositori kosong, tampilkan modal
        return;
      }

      setRepos(data);
      router.push(`/projects`);
    } catch (error) {
      setShowModal(true); // Jika user tidak ditemukan, tampilkan modal
    }
  };

  return (
    <>
      <Head>
        <title>Best Practice</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="search-container">
        <h1 className="search-title">GitHub Repository Finder</h1>
        <div className="input-search">
        <input
          className="search-box"
          placeholder="search name github"
          type="text"
          value={input}
          onChange={(e) => setInput(e.target.value)}
        />
        <LitButton onClick={handleSearch}>Search</LitButton>
        </div>
      </div>

      {/* Menggunakan LitModal */}
      {showModal && (
        <LitModal onClose={() => setShowModal(false)}>
          <h2>User Not Found</h2>
          <p>The GitHub username you entered does not exist.</p>
        </LitModal>
      )}
    </>
  )
}
